# Generated by Django 5.0.7 on 2024-08-05 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LMS', '0005_forum_notification_post_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('module',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='LMS.module')),
            ],
        ),
    ]
