# Generated by Django 5.0.7 on 2024-08-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LMS', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Liên kết', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                    to='LMS.filetype'),
        ),
    ]
