# Generated by Django 5.0.7 on 2024-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LMS', '0009_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Trắc nghiệm'), (1, 'Tự luận')]),
        ),
    ]
