# Generated by Django 5.0.7 on 2024-08-05 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
