# Generated by Django 5.0.7 on 2024-08-06 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_test_num_questions_test_test_type_essayanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='essay_answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
