# Generated by Django 5.0.7 on 2024-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_course_is_active_coursemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
