# Generated by Django 5.0.7 on 2024-09-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0019_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('Tập tin', 'Tập tin'), ('Liên kết', 'Liên kết')], editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
