# Generated by Django 5.0.7 on 2024-09-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0022_alter_course_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.question'),
        ),
    ]
