# Generated by Django 5.0.7 on 2024-09-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0023_alter_essayanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
