# Generated by Django 5.0.7 on 2024-10-03 00:39

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0024_alter_answer_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_degree_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='front_degree')),
                ('back_degree_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='back_degree')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
